#!/usr/bin/env bash
echo "--------> Creating the bucket" 
if [ -z "$1" ]; then
    echo "Bucket name should be specified"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket --bucket "$BUCKET_NAME" \
    --create-bucket-configuration="LocationConstraint=ap-south-2"



